title: Nana Adjei Manu
description: Computer Programmer and Researcher
url: "https://nanamanu.com"
author: Nana Adjei Manu
email: n.k.a.manu06@gmail.com
github_username: naamanu
twitter_username: nmanu__

markdown: kramdown
theme: null
plugins:
  - jekyll-feed
